# Generated by Django 5.2.17 on 2026-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='post_creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
