# Generated by Django 5.2.17 on 2026-08-24 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_opinion_post_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='reporter',
            field=models.ManyToManyField(blank=True, related_name='reporters_of_this_opinion', to=settings.AUTH_USER_MODEL),
        ),
    ]
