# Generated by Django 5.2.17 on 2026-08-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_opinion_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
